apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pod-node-cni
  namespace: peer-pods-example
data:
  10-peer-pods.conflist: |
    {
      "cniVersion": "1.0.0",
      "name": "peer-pods",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "cni0",
          "isGateway": true,
          "ipMasq": true,
          "hairpinMode": true,
          "ipam": {
            "type": "host-local",
            "ranges": [[{"subnet": "10.245.0.0/24"}]],
            "routes": [{"dst": "0.0.0.0/0"}]
          }
        },
        {
          "type": "portmap",
          "capabilities": {"portMappings": true}
        }
      ]
    }
  99-loopback.conf: |
    {
      "cniVersion": "1.0.0",
      "name": "lo",
      "type": "loopback"
    }
