apiVersion: v1
kind: Namespace
metadata:
  name: peer-pods-example
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
