apiVersion: sandbox.caa.mnicloud.jp/v1alpha1
kind: PodSandboxClass
metadata:
  name: default
spec:
  runnerImage: ghcr.io/mni-cloud/cloud-api-adaptor-provider-kubernetes-runner-cloud-hypervisor:latest
  podVMImage: ghcr.io/mni-cloud/cloud-api-adaptor-provider-kubernetes-podvm:latest
  networkMTU: 1500
  runtimeAssetsDir: /opt/kata
  memoryOverheadMiB: 256
  startupGraceSeconds: 30
