apiVersion: apps/v1
kind: Deployment
metadata:
  name: caa-provider-kubernetes-controller-manager
  namespace: caa-provider-kubernetes-system
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Always
          args:
            - --namespace=caa-provider-kubernetes-system
            - --class-name=juneau
            - --leader-elect
