apiVersion: sandbox.caa.mnicloud.jp/v1alpha1
kind: PodSandboxClass
metadata:
  name: juneau
spec:
  runnerImage: localhost:5005/pod-sandbox-runner-kubernetes:dev
  podVMImage: localhost:5005/podvm-kubernetes:dev
  networkMTU: 1400
  annotations:
    juneau.loutres.me/subnet: default
  nodeSelector:
    mnicloud.jp/kata: "true"
  kataDir: /opt/kata
  memoryOverheadMiB: 256
  startupGraceSeconds: 30
